-- AI triage: per-exception diagnosis + recommended action, generated by
-- Claude when the exception opens. Written by the sweep (service role);
-- readable by the dashboard through the existing table-level select.

alter table public.exceptions add column triage jsonb;
